{
  "name": "ChatMuffler",
  "main": "Thunder33345\\Muffler\\Muffler",
  "author": "Thunder33345",
  "description": "Muffle helps you muffle your players and keep then nice and silent!",
  "website": "https://github.com/Muffler/Muffler",
  "version": "1.0.0",
  "api": [
    "3.0.0"
  ],
  "permission": {
    "chatmuffler": {
      "defualt": "false",
      "description": "Chat muffler main node",
      "children": {
        "chatmuffler.bypass": {
          "defualt": "op",
          "description": "Bypass All Muffled Restriction",
          "children": {
            "chatmuffler.bypass.chat": {
              "defualt": "op",
              "description": "Bypass Muffled Chat Restriction"
            },
            "chatmuffler.bypass.user": {
              "defualt": "op",
              "description": "Bypass User Muffled Restriction"
            }
          }
        },
        "chatmuffler.muffleuser": {
          "defualt": "op",
          "description": "Allow Muting Other Users"
        },
        "chatmuffler.mufflechat": {
          "defualt": "op",
          "description": "Allow Muting Chat"
        },
        "chatmuffler.muffleinfo": {
          "defualt": "true",
          "description": "Allow Using Muffle Info",
          "children": {
            "chatmuffler.muffleinfo.self": {
              "defualt": "true",
              "description": "Allow Using Muffle Info On Self"
            },
            "chatmuffler.muffleinfo.other": {
              "defualt": "op",
              "description": "Allow Using Muffle Info On Others"
            }
          }
        }
      }
    }
  }
}